apiVersion: v1
kind: Pod
metadata:
  name: interception-request-handler
  namespace: interception
  labels:
          app: interception-request-handler
spec:
  containers:
  - name: interception-request-handler
    image: infocomsrl/interception-request-handler:0.1
    env:
    - name: LOGGERLEVEL
      value: "DEBUG"
    - name: RESTSERVERADDRESS
      value: "0.0.0.0"
    - name: RESTSERVERPORT
      value: "5004"
    - name: KAFKAADDRESS
      value: "kafka-service.astrid-kube"
    - name: KAFKAPORT
      value: "9092"
    - name: KAFKATOPIC
      value: "interception"
    - name: CONTEXTBROKERADDRESS
      value: "0.0.0.0"
    - name: CONTEXTBROKERPORT
      value: "0"
    - name: CONTEXTBROKERUSER
      value: "astrid"
    - name: CONTEXTBROKERPASSWORD
      value: "none"

    imagePullPolicy: IfNotPresent
  restartPolicy: Never
  nodeSelector:
    name: compute03

