apiVersion: v1
kind: Service
metadata:
  name: interception-core-handler
  namespace: interception
spec:
  selector:
    app: core-handler
  clusterIP: None
  ports:
  - name: rest
    port: 5003
    targetPort: 5003

