apiVersion: v1
kind: Pod
metadata:
  name: interception-core-handler
  namespace: interception
  labels:
          app: interception-core-handler
spec:
  containers:
  - name: interception-core-handler
    image: infocomsrl/interception-core-handler:0.1
    env:
    - name: LOGGERLEVEL
      value: "DEBUG"
    - name: INTERFACE
      value: "eth0"
    - name: INTERCEPTIONPATH
      value: "/root/interceptions/"
    - name: RESTSERVERADDRESS
      value: "0.0.0.0"
    - name: RESTSERVERPORT
      value: "5003"
    - name: POLYCUBEADDRESS
      value: "127.0.0.1"
    - name: POLYCUBEPORT
      value: "9000"
    - name: KAFKAADDRESS
      value: "0.0.0.0"
    - name: KAFKAPORT
      value: "5002"
    - name: KAFKATOPIC
      value: "interception"
    - name: LOGSTASHADDRESS
      value: "lea-interface"
    - name: LOGSTASHMSGPORT
      value: "5959"
    - name: LOGSTASHDATAPORT
      value: "5960"
    - name: LOGSTASHVERSION
      value: "1"
    - name: LOGVOIPPATH
      value: "./logs/"
    - name: LOGVOIPFILENAME
      value: "containerLogs.log"
    - name: LOGVOIPREADINGTIME
      value: "0.5"
    - name: POLYCUBEISENABLED
      value: "true"
    - name: LIBPCAPISENABLED
      value: "false"
    - name: TCPSERVERADDRESS
      value: "0.0.0.0"
    - name: TCPSERVERPORT
      value: "0"
    volumeMounts:
    - name: interception-data
      mountPath: /root/interceptions

    imagePullPolicy: IfNotPresent

  - name: polycube
    image: polycubenetwork/polycube:latest
    command: ["/bin/bash", "-c"]
    args: ["whoami; polycubed"]
    volumeMounts:
    - name: etc-localtime
      mountPath: /etc/localtime
      readOnly: true
    - name: lib-modules
      mountPath: /lib/modules
      readOnly: true
    - name: usr-src
      mountPath: /usr/src
      readOnly: true
    - name: dev-net-tun
      mountPath: /dev/net/tun
      readOnly: true
    - name: interception-data
      mountPath: /root/interceptions
    securityContext:
      runAsUser: 0
      capabilities:
         add:
           - all
    imagePullPolicy: IfNotPresent

  - name: lcp
    image: astridproject/lcp:master
    command: ["/bin/sh", "-c"]
    args: ["apk --update add curl; python3 main.py"]
    env:
      - name: LCP_HOST
        value: "0.0.0.0"
      - name: LCP_PORT
        value: "4000"
      - name: LCP_HTTPS
        value: "false"
      - name: LCP_AUTH_ENABLED
        value: "true"
      - name: LCP_AUTH_HEADER_PREFIX
        value: "ASTRID"
      - name: LCP_AUTH_SECRET_KEY
        value: "astrid-secret-key"
      - name: LCP_ELASTIC_APM_ENABLED
        value: "false"
      - name: LCP_ELASTIC_APM_SERVER
        value: "http://localhost:8200"
      - name: LCP_POLYCUBE_HOST
        value: "localhost"
      - name: LCP_POLYCUBE_PORT
        value: "9000"
      - name: LCP_POLYCUBE_TIMEOUT
        value: "20s"
      - name: LCP_LOG_CONFIG
        value: "log.yaml"
    imagePullPolicy: IfNotPresent
  
  restartPolicy: Never
  nodeSelector:
    kernel: "5"
  volumes:
  - name: lib-modules
    hostPath:
       path: /lib/modules
  - name: usr-src
    hostPath:
       path: /usr/src
  - name: etc-localtime
    hostPath:
       path: /etc/localtime
  - name: dev-net-tun
    hostPath:
       path: /dev/net/tun
  - name: interception-data
    emptyDir: {}

