apiVersion: v1
kind: Pod
metadata:
  name: lea-interface
  namespace: interception
  labels:
          app: lea-interface
spec:
  containers:
  - name: lea-interface
    image: infocomsrl/lea-interface:0.1
    env:
    - name: LOGGERLEVEL
      value: "DEBUG"
    - name: TCPSERVERADDRESS
      value: "0.0.0.0"
    - name: TCPSERVERPORT
      value: "5004"
    - name: KAFKAADDRESS
      value: "kafka-service.astrid-kube"
    - name: KAFKAPORT
      value: "0"
    - name: KAFKATOPIC
      value: "interception"
    imagePullPolicy: IfNotPresent

  - name: logstash
    image: docker.elastic.co/logstash/logstash:7.8.0
    volumeMounts:
    - name: pipelines
      mountPath: /usr/share/logstash/pipeline
    - name: config
      mountPath: /usr/share/logstash/config/logstash.yml
      subPath: logstash.yml
    - name: pipelines-config
      mountPath: /usr/share/logstash/config/pipelines.yml
      subPath: pipelines.yml
    securityContext:
      runAsUser: 0
    imagePullPolicy: IfNotPresent

  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    securityContext:
      runAsUser: 0
    ports:
    - containerPort: 9200   
    env:
      - name: INSTALLATION_PATH
        value: /usr/share/elasticsearch
      - name: ELASTICSEARCH_PORT
        value: "9200"
      - name: ELASTICSEARCH_MONITORING_ENABLED
        value: "false"
      - name: ELASTICSEARCH_TRANSPORT_TCP_PORT
        value: "9300"
    volumeMounts:
      - name: elasticsearch-config
        mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
        subPath: elasticsearch.yml
        #      - name: elasticsearch-data
        #        mountPath: /usr/share/elasticsearch/data/
        #      - name: node
        #        mountPath: /node

  - name: kibana
    image: docker.elastic.co/kibana/kibana:7.8.0
    env:
      - name: ELASTICSEARCH_URL
        value: http://localhost:9200
    ports:
    - containerPort: 5601
    volumeMounts:
      - name: kibana-config
        mountPath: /usr/share/kibana/config/kibana.yml
        subPath: kibana.yml

  restartPolicy: Never
  nodeSelector:
    name: compute03
 
  volumes:
  - name: pipelines
    configMap:
      name: lea-interface-configmap
      items:
        - key: logstash_for_call_information.conf
          path: logstash_for_call_information.conf
        - key: logstash_for_interception_saving.conf
          path: logstash_for_interception_saving.conf
  - name: config
    configMap:
      name: lea-interface-configmap
      defaultMode: 0666
      items:
        - key: logstash.yml
          path: logstash.yml
  - name: pipelines-config
    configMap:
       name: lea-interface-configmap
       defaultMode: 0666
       items:
        - key: pipelines.yml
          path: pipelines.yml
  - name: elasticsearch-config
    configMap:
       name: lea-interface-configmap
       defaultMode: 0666
       items:
        - key: elasticsearch.yml
          path: elasticsearch.yml
  - name: kibana-config
    configMap:
       name: lea-interface-configmap
       defaultMode: 0666
       items:
         - key: kibana.yml
           path: kibana.yml
