apiVersion: v1
kind: Service
metadata:
  name: interception-request-handler
  namespace: interception
spec:
  selector:
    app: interception-request-handler
  clusterIP: None
  ports:
  - name: rest
    port: 5004
    targetPort: 5004

